### ISSUE TITLE
Secret and Access Key - Response 500

### ISSUE THREAD

**Issue by mdy007** [xmigrate/xmigrate#49]
Hi Xmigrate,

We are facing the Credentials issue as below snapshot, even we have given a right Secret and Access with respective role, Application is not detecting and showing 500 error. Please give an update on this.

![image](https://user-images.githubusercontent.com/34213219/104355438-adf15e80-5530-11eb-93b1-a39e6025fd30.png)

![image](https://user-images.githubusercontent.com/34213219/104355291-77b3df00-5530-11eb-846d-a8c670098b84.png)

Regards,
S.Mohamed.
Devops Engineer.

**Comment by iamvishnuks** [comment]
I checked and found there are no issues. However there is one UX flow, instead of accepting in the order of access key and secret key, in xmigrate interface it is secret key and access key. By nature all the AWS engineers and architects are tempted to input access key and then secret key. Please check and confirm..  👍

**Comment by iamvishnuks** [comment]
The issue is resolved
